### PR TITLE
Enhance documentation and readability of shell_connector.bash

### PR DESCRIPTION
**Pull request by ngirard**
This PR includes several improvements to the shell_connector.bash script:

- The `mkBound` function has been updated with more readable constants and additional comments.
- The `newConnector` function has been enhanced with comprehensive comments following a standard template, improving its readability and providing a better understanding of its purpose, parameters, return value, constants, and additional notes.
- The `mySqlReq` function has been updated to allow reading SQL commands from standard input if none are provided as arguments, and to remove any trailing semicolon from the SQL command before execution. The function now also includes a configurable timeout parameter.
- The global variables used in the script have been moved to the top and documented.
- Several legacy comment blocks have been replaced with comprehensive function documentation, including synopsis, parameters, return values, constants, and additional notes.
- Various in-line comments have been added to explain the purpose and functioning of different parts of the script.

### CODE REVIEW

**Comment by F-Hauri** [comment]
Introducing a timeout will drop down overall performance of your whole script by *number of request* `x` *timeout*!
It's a bad idea!
This is the reason I used `read -t 0` **before** using timeout on *errors*, in order to limit the use of timeout to answer **that contain errors**.

**Comment by ngirard** [comment]
I see your point, and I'm aware of that. Apologies for not making a less granular PR.

As I said in #2, I dropped the `read -t 0` with the intent of reintroducing them later when dealing with improving error handling.

Also, the `mySqlReq` function as I found it wouldn't work with this simple test:
```
#!/usr/bin/env bash

source ./shell_connector.bash

# Establish a connection to an in-memory SQLite database
newSqlConnector /usr/bin/sqlite3 ":memory:"

# Execute an SQL query to create a table
mySqlReq res 'CREATE TABLE test (id INTEGER PRIMARY KEY, name TEXT);'

# Execute an SQL query to insert data into the table
mySqlReq res "INSERT INTO test (name) VALUES ('John Doe');"

# Execute an SQL query to select data from the table
mySqlReq res 'SELECT * FROM test;'

# Print the results
declare -p res_h res_e
```

which stalled while executing one of the `read`s.

I chose to bring the code in a simple form and usable state, with the intent of coming back to the data reading once I have proper unit tests, instead of testing manually against SQLite only.

All in all: this is a work in progress.

**Comment by F-Hauri** [comment]
>     # Establish a connection to an in-memory SQLite database
>      newSqlConnector /usr/bin/sqlite3 ":memory:"

Care: You have to ask sqlite to use `\t` as separator!

    . shell_connector.sh
    newSqlConnector /usr/bin/sqlite3  $'-separator \t -header :memory:'

    mySqlReq res 'CREATE TABLE test (id INTEGER PRIMARY KEY, name TEXT);'

    mySqlReq res "INSERT INTO test (name) VALUES ('John Doe');"

    mySqlReq res 'SELECT * FROM test;'

    declare -p res{,_e,_h}
    declare -a res=([0]=$'1\tJohn Doe')
    declare -a res_e=()
    declare -a res_h=([0]="id" [1]="name")

**Comment by F-Hauri** [comment]
Did you try to execute them:

    ./shell_connector.sh

Script on my site hold a full demo if run instead of sourced:


    #
    # Exit here if script is sourced
    [ "$0" = "$BASH_SOURCE" ] || {
        true
        return 0
    }

    ###
    ### Demo-sample: define/open 3 connectors to `bc`, `date` and `sqlite`,
    ### for interactive use from main bash script.
    ###

**Comment by F-Hauri** [comment]
I've tested commands arguments for SQLite, MariaDB (MySQL) and PostgreSQL:

    # newSqlConnector /usr/bin/sqlite3 $'-separator \t -header /dev/shm/test.sqlite'
    # newSqlConnector /usr/bin/psql $'-Anh host -F \t --pset=footer=off user'
    # newSqlConnector /usr/bin/mysql '-f --abort-source-on-error=0 -h host -B -p db'

**Comment by ngirard** [comment]
> Care: You have to ask sqlite to use `\t` as separator!

Ah great, that might be the reason why it was stalling then !

I'll come back to this hopefully tomorrow: I'll add further commits, reintroducing the `read -t 0` with an early return and try and get rid of the timeouts.

Thanks for your time, cheers !

**Comment by F-Hauri** [comment]
>  that might be the reason..

That's the reason! `${line[0]}` won't ever match `$bound` if not well parsed.

    [ "$line" != "$bound" ] 

... And again, I will prefer direct contact by mail to github at f-hauri.ch than continuing to post my improvements on this platform... ;-)

But thanks again for your work and your interest!

**Pull request merged**
